# Generated by Django 3.1.7 on 2021-04-04 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_musicalstorehome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicalstorehome',
            old_name='first_name',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='musicalstorehome',
            old_name='profile_pic',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='musicalstorehome',
            old_name='last_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='musicalstorehome',
            name='email',
        ),
    ]
