# Generated by Django 3.1.7 on 2021-04-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210403_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicalStoreReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('desc', models.CharField(max_length=50)),
            ],
        ),
    ]
