# Generated by Django 3.1.7 on 2021-04-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_musicalstoreinstrument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicalstorereg',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='musicalstorereg',
            name='name',
        ),
        migrations.AddField(
            model_name='musicalstorereg',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='musicalstorereg',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='musicalstorereg',
            name='firstname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musicalstorereg',
            name='lastname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musicalstorereg',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='musicalstorereg',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musicalstorereg',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='musicalstorereg',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
