# Generated by Django 3.1.7 on 2021-04-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210409_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicalstoreinstrument',
            name='name',
        ),
        migrations.AddField(
            model_name='musicalstoreinstrument',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='musicalstoreinstrument',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='musicalstoreinstrument',
            name='subtitle',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musicalstoreinstrument',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musicalstoreinstrument',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='musicalstoreinstrument',
            name='desc',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
