# Generated by Django 3.1.7 on 2021-04-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210409_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicalStoreRegShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile', models.CharField(max_length=50, null=True)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('username', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('created', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='musicalstorereg',
            name='mobile',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
