# Generated by Django 3.1.7 on 2021-04-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210411_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicalStoreInstrumentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('subtitle', models.CharField(max_length=50, null=True)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('desc', models.CharField(max_length=50, null=True)),
                ('price', models.IntegerField(null=True)),
                ('created', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(null=True)),
            ],
        ),
    ]
