# Generated by Django 3.1.7 on 2021-04-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_musicalstoreinstrumentdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicalstorehome',
            old_name='img',
            new_name='img1',
        ),
        migrations.RemoveField(
            model_name='musicalstorehome',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='musicalstorehome',
            name='name',
        ),
        migrations.AddField(
            model_name='musicalstorehome',
            name='btntext1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musicalstorehome',
            name='btntext2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musicalstorehome',
            name='btntext3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musicalstorehome',
            name='btntext4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musicalstorehome',
            name='btntext5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musicalstorehome',
            name='btntext6',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musicalstorehome',
            name='btntext7',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musicalstorehome',
            name='copyrighttext',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musicalstorehome',
            name='img2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='musicalstorehome',
            name='img3',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='musicalstorehome',
            name='img4',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='musicalstorehome',
            name='logotext',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musicalstorehome',
            name='subdesc1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musicalstorehome',
            name='subdesc2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musicalstorehome',
            name='subdesc3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musicalstorehome',
            name='subdesc4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musicalstorehome',
            name='subtitle1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musicalstorehome',
            name='subtitle2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musicalstorehome',
            name='subtitle3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musicalstorehome',
            name='subtitle4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musicalstorehome',
            name='text1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musicalstorehome',
            name='text2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musicalstorehome',
            name='text3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musicalstorehome',
            name='text4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musicalstorehome',
            name='text5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musicalstorehome',
            name='title1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musicalstorehome',
            name='title2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musicalstorehome',
            name='title3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musicalstorehome',
            name='title4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musicalstorehome',
            name='title5',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
