# Generated by Django 3.1.7 on 2021-04-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20210411_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicalstorehome',
            old_name='logotext',
            new_name='logotext1',
        ),
        migrations.AddField(
            model_name='musicalstorehome',
            name='logotext2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
