# Generated by Django 3.1.7 on 2021-04-11 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20210411_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicalstorehome',
            old_name='btntext7',
            new_name='text6',
        ),
        migrations.RenameField(
            model_name='musicalstorehome',
            old_name='title5',
            new_name='text7',
        ),
    ]
