# Generated by Django 3.1.7 on 2021-04-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20210411_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicalstorehome',
            name='subdesc1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musicalstorehome',
            name='subdesc2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musicalstorehome',
            name='subdesc3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musicalstorehome',
            name='subdesc4',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
