# Generated by Django 3.1.7 on 2021-04-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20210411_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicalstorehome',
            name='btntext1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musicalstorehome',
            name='btntext2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musicalstorehome',
            name='btntext3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musicalstorehome',
            name='btntext4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musicalstorehome',
            name='btntext5',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musicalstorehome',
            name='btntext6',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musicalstorehome',
            name='copyrighttext',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musicalstorehome',
            name='logotext1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musicalstorehome',
            name='logotext2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musicalstorehome',
            name='subtitle1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musicalstorehome',
            name='subtitle2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musicalstorehome',
            name='subtitle3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musicalstorehome',
            name='subtitle4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musicalstorehome',
            name='text1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musicalstorehome',
            name='text2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musicalstorehome',
            name='text3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musicalstorehome',
            name='text4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musicalstorehome',
            name='text5',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musicalstorehome',
            name='text6',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musicalstorehome',
            name='text7',
            field=models.CharField(max_length=5255, null=True),
        ),
        migrations.AlterField(
            model_name='musicalstorehome',
            name='title1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musicalstorehome',
            name='title2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musicalstorehome',
            name='title3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musicalstorehome',
            name='title4',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
