# Generated by Django 3.1.7 on 2021-04-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20210411_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicalstoreinstrument',
            name='desc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musicalstoreinstrument',
            name='subtitle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musicalstoreinstrument',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musicalstoreinstrumentdetail',
            name='desc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musicalstoreinstrumentdetail',
            name='subtitle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musicalstoreinstrumentdetail',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
