# Generated by Django 3.1.7 on 2021-04-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20210411_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicalstoreinstrument',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
