# Generated by Django 3.1.7 on 2021-04-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_musicalstorecontactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicalstorecontactus',
            old_name='address',
            new_name='address1',
        ),
        migrations.AddField(
            model_name='musicalstorecontactus',
            name='address2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='musicalstorecontactus',
            name='address3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musicalstorecontactus',
            name='email',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='musicalstorecontactus',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
