# Generated by Django 3.1.7 on 2021-04-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20210414_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicalstorehome',
            name='btntext7',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='musicalstorehome',
            name='btntext8',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musicalstorecontactus',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
