# Generated by Django 3.1.7 on 2021-04-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_musicalstoreaboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicalstorereg',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
