# Generated by Django 3.1.7 on 2021-04-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_auto_20210416_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicalstorereg',
            name='img',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
