# Generated by Django 3.1.7 on 2021-04-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_auto_20210418_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicalstorehome',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='musicalstorehome',
            name='userid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
